In [32]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [33]:
import pandas as pd
df = pd.read_csv('Student_Performance.csv')
df.head(3)

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0

# We have string value on ExtraCurricular Activities

In [34]:
df['Extracurricular Activities'].unique()

array(['Yes', 'No'], dtype=object)

In [35]:
df['Extracurricular Activities']=df['Extracurricular Activities'].map({"Yes":1,"No":0})
df['Extracurricular Activities'].head(3)

0    1
1    0
2    1
Name: Extracurricular Activities, dtype: int64

In [36]:
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,1,9,1,91.0
1,4,82,0,4,2,65.0
2,8,51,1,7,2,45.0
3,5,52,1,5,2,36.0
4,7,75,0,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,1,4,2,23.0
9996,7,64,1,8,5,58.0
9997,6,83,1,8,5,74.0
9998,9,97,1,7,0,95.0
9999,7,74,0,8,1,64.0

In [37]:
x=df.drop("Performance Index",axis=1)
y=df["Performance Index"]

In [38]:
x.shape

(10000, 5)

In [39]:
y.shape

(10000,)

In [40]:
5x.head(3)

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
0,7,99,1,9,1
1,4,82,0,4,2
2,8,51,1,7,2

In [41]:
y.head(3)

0    91.0
1    65.0
2    45.0
Name: Performance Index, dtype: float64

In [42]:
model = LinearRegression()
model.fit(x,y)

LinearRegression()

In [43]:
model.coef_

array([2.85298205, 1.01843419, 0.61289758, 0.48055975, 0.19380214])

In [44]:
model.intercept_

np.float64(-34.0755880919139)

In [51]:
Hours_Studied=int(input("Enter The Hours Studied by Student : "))
Previous_Scores = int(input("Enter The Previous Scores of the Student :"))
Extracurricular_Activities = int(input("Enter The Extracurricular Activities of Student (Valid 1 or 0) :"))
if Extracurricular_Activities>1 or Extracurricular_Activities<0:
    print("Invalid Extracurricular Activities")
Sleep_Hours=int(input("Enter The Sleep Hours of Student:"))
Sample_Question_Papers_Practiced = int(input("Enter The Sample Question Papers Practiced of Student  :"))

In [52]:
x.head(2)

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
0,7,99,1,9,1
1,4,82,0,4,2

In [57]:
my_input=pd.DataFrame([[Hours_Studied,Previous_Scores,Extracurricular_Activities,Sleep_Hours,Sample_Question_Papers_Practiced]],columns=["Hours Studied","Previous Scores","Extracurricular Activities","Sleep Hours","Sample Question Papers Practiced"])

In [58]:
my_input.shape

(1, 5)

In [59]:
my_input.columns

Index(['Hours Studied', 'Previous Scores', 'Extracurricular Activities',
       'Sleep Hours', 'Sample Question Papers Practiced'],
      dtype='object')

In [60]:
model.predict(my_input)

array([62.41759223])